# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-taggings}
  s.version = "0.11.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Piotr Solnica"]
  s.date = %q{2010-10-14}
  s.description = %q{DataMapper plugin that adds the possibility to tag models}
  s.email = %q{piotr.solnica@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "dm-is-taggable.gemspec",
     "lib/dm-taggings.rb",
     "lib/dm-taggings/is/tag.rb",
     "lib/dm-taggings/is/taggable.rb",
     "lib/dm-taggings/is/tagger.rb",
     "lib/dm-taggings/is/tagging.rb",
     "lib/dm-taggings/is/version.rb",
     "lib/dm-taggings/spec/taggable_shared_spec.rb",
     "lib/dm-taggings/spec/tagger_shared_spec.rb",
     "spec/fixtures/models.rb",
     "spec/integration/post_spec.rb",
     "spec/integration/tag_spec.rb",
     "spec/integration/taggable_spec.rb",
     "spec/integration/user_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/hoe.rb",
     "tasks/yard.rake",
     "tasks/yardstick.rake"
  ]
  s.homepage = %q{http://github.com/solnic/dm-taggings}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tagging plugin for DataMapper}
  s.test_files = [
    "spec/integration/taggable_spec.rb",
     "spec/integration/post_spec.rb",
     "spec/integration/tag_spec.rb",
     "spec/integration/user_spec.rb",
     "spec/fixtures/models.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-constraints>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-is-remixable>, ["~> 1.0.2"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<yard>, ["~> 0.5"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-constraints>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-is-remixable>, ["~> 1.0.2"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<yard>, ["~> 0.5"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-constraints>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-is-remixable>, ["~> 1.0.2"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<yard>, ["~> 0.5"])
  end
end

